appenders:
  file_logger:
    kind: rolling_file
    path: "log/log.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(pdt)} - {h({l})}: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 100
        pattern: "logs/log_{}.log"
root:
  level: trace
  appenders:
    - file_logger